### ISSUE TITLE
Slack icon fix

### ISSUE THREAD

**Issue by BlueManCZ** [bilelmoussaoui/Hardcode-Tray#673]
Did Slack again change icon location or something? The current fix doesn't seem to work with Slack 4.11.3.

**Comment by varlesh** [comment]
please check with new updates

**Comment by BlueManCZ** [comment]
Okay, sorry, my bad. It worked before, I just forgot to revert before applying another fix. Now, after your update, it crashes, so please return to the previous one and you can close this.

**Comment by varlesh** [comment]
@BlueManCZ But you added Slack support))
I'm grep Base64 tray icons and this located on `dist/slack.json`
LOG:
```
 File "/usr/bin/hardcode-tray", line 121, in <module>
    App.execute()
  File "/usr/lib/python3.8/site-packages/HardcodeTray/app.py", line 120, in execute
    delta = app.do_action(action)
  File "/usr/lib/python3.8/site-packages/HardcodeTray/modules/applications/application.py", line 148, in do_action
    self.install()
  File "/usr/lib/python3.8/site-packages/HardcodeTray/decorators.py", line 58, in wrapper
    func(app)
  File "/usr/lib/python3.8/site-packages/HardcodeTray/modules/applications/application.py", line 96, in install
    self.execute(Action.APPLY)
  File "/usr/lib/python3.8/site-packages/HardcodeTray/modules/applications/helpers/binary.py", line 50, in execute
    self.install_icon(icon, icon_path)
  File "/usr/lib/python3.8/site-packages/HardcodeTray/modules/applications/b64electron.py", line 50, in install_icon
    file_content = asar.read_file(target).decode()
AttributeError: 'NoneType' object has no attribute 'decode'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] Нет такого файла или каталога: '/var/crash/_usr_bin_hardcode-tray.0.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/hardcode-tray", line 121, in <module>
    App.execute()
  File "/usr/lib/python3.8/site-packages/HardcodeTray/app.py", line 120, in execute
    delta = app.do_action(action)
  File "/usr/lib/python3.8/site-packages/HardcodeTray/modules/applications/application.py", line 148, in do_action
    self.install()
  File "/usr/lib/python3.8/site-packages/HardcodeTray/decorators.py", line 58, in wrapper
    func(app)
  File "/usr/lib/python3.8/site-packages/HardcodeTray/modules/applications/application.py", line 96, in install
    self.execute(Action.APPLY)
  File "/usr/lib/python3.8/site-packages/HardcodeTray/modules/applications/helpers/binary.py", line 50, in execute
    self.install_icon(icon, icon_path)
  File "/usr/lib/python3.8/site-packages/HardcodeTray/modules/applications/b64electron.py", line 50, in install_icon
    file_content = asar.read_file(target).decode()
AttributeError: 'NoneType' object has no attribute 'decode'

```

**Comment by varlesh** [comment]
This extracted app.asar. You can check it
[slack-app-asar.tar.gz](https://github.com/bilelmoussaoui/Hardcode-Tray/files/5724539/slack-app-asar.tar.gz)

**Comment by BlueManCZ** [comment]
Yes, I just wanted to say that I was wrong in this issue. It worked fine.

**Comment by varlesh** [comment]
It' from 4.12. You use this version?

**Comment by BlueManCZ** [comment]
I use 4.11.3

**Comment by BlueManCZ** [comment]
Did something change from 4.11.3 to 4.12?

**Comment by varlesh** [comment]
I'm not understand... and confused

**Comment by varlesh** [comment]
Earlier i'm grep icon and this located on `dist/slack.json`
BUT NOW it's grep on `dist/main.bundle.js`
WTF???!!!

**Comment by BlueManCZ** [comment]
Yes, I'm confused too now. :smile:

**Comment by BlueManCZ** [comment]
I don't even see slack.json in your asar.

**Comment by varlesh** [comment]
omg lol PLEASE excuse me. I'm grep hardcode-tray database earlier....
LOL ))) 
It's very funny issue

**Comment by varlesh** [comment]
@BlueManCZ wrong issue, wrong commit = revert all!!!
LOL

**Comment by BlueManCZ** [comment]
Yes, this doesn't happen very often. :smile:

**Comment by varlesh** [comment]
@BlueManCZ You know python. Maybe you find time and drop other conversions tools...
Inkscape, Imagemagic and etc... use only RSVGConvert - it's worked good for mostly Linux desktops
PS: option `--conversion-tool {Inkscape,CairoSVG,RSVGConvert,SVGExport,ImageMagick}` causes many problems on users

**Comment by varlesh** [comment]
https://github.com/bilelmoussaoui/Hardcode-Tray/issues/672
https://github.com/bilelmoussaoui/Hardcode-Tray/issues/630
https://github.com/bilelmoussaoui/Hardcode-Tray/issues/578

**Comment by BlueManCZ** [comment]
Create a new issue for this and mention me. I will see when I get time to look into it.

**Comment by varlesh** [comment]
This already here: https://github.com/bilelmoussaoui/Hardcode-Tray/issues/578

**Comment by varlesh** [comment]
@BlueManCZ  If you interest develop hardcode-tray we can request vote on @bilelmoussaoui to add you on membership))

**Comment by BlueManCZ** [comment]
Yes, I can collaborate with you. I'll see if I can find some time.
